packages:
  - apps/*
  - packages/*
  - examples/*

shamefullyHoist: true
strictPeerDependencies: false

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false
  '@nestjs/core': false
  '@swc/core': false
  workerd: false
  better-sqlite3: true
  isolated-vm: true
  sharp: true

overrides:
  minimark: 0.2.0
  '@nuxtjs/mcp-toolkit': ^0.16.1

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  # Nuxt
  - '@nuxt/*'
  - '@nuxtjs/*'
  - 'nuxt'
  - 'nuxt-*'
  # Vercel
  - '@vercel/*'
  - '@ai-sdk/*'
  - 'ai'
  # Other
  - '@databuddy/nuxt'
