/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiHelloRouteImport } from './routes/api/hello'
import { Route as ApiOrderRouteImport } from './routes/api/order'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/api/hello',
  path: '/api/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrderRoute = ApiOrderRouteImport.update({
  id: '/api/order',
  path: '/api/order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/hello': typeof ApiHelloRoute
  '/api/order': typeof ApiOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/hello': typeof ApiHelloRoute
  '/api/order': typeof ApiOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/hello': typeof ApiHelloRoute
  '/api/order': typeof ApiOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/admin' | '/api/checkout' | '/api/hello' | '/api/order'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/admin' | '/api/checkout' | '/api/hello' | '/api/order'
  id:
    | '__root__'
    | '/'
    | '/api/admin'
    | '/api/checkout'
    | '/api/hello'
    | '/api/order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiHelloRoute: typeof ApiHelloRoute
  ApiOrderRoute: typeof ApiOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hello': {
      id: '/api/hello'
      path: '/api/hello'
      fullPath: '/api/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/order': {
      id: '/api/order'
      path: '/api/order'
      fullPath: '/api/order'
      preLoaderRoute: typeof ApiOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiHelloRoute: ApiHelloRoute,
  ApiOrderRoute: ApiOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
