import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'nuxt/module': 'src/nuxt/module.ts',
    'nitro/module': 'src/nitro/module.ts',
    'nitro/plugin': 'src/nitro/plugin.ts',
    'nitro/errorHandler': 'src/nitro/errorHandler.ts',
    'nitro/v3/index': 'src/nitro-v3/index.ts',
    'nitro/v3/module': 'src/nitro-v3/module.ts',
    'nitro/v3/useLogger': 'src/nitro-v3/useLogger.ts',
    'nitro/v3/middleware': 'src/nitro-v3/middleware.ts',
    'nitro/v3/plugin': 'src/nitro-v3/plugin.ts',
    'nitro/v3/errorHandler': 'src/nitro-v3/errorHandler.ts',
    'runtime/client/log': 'src/runtime/client/log.ts',
    'runtime/client/plugin': 'src/runtime/client/plugin.ts',
    'runtime/server/useLogger': 'src/runtime/server/useLogger.ts',
    'runtime/server/routes/_evlog/ingest.post': 'src/runtime/server/routes/_evlog/ingest.post.ts',
    'runtime/utils/parseError': 'src/runtime/utils/parseError.ts',
    'error': 'src/error.ts',
    'logger': 'src/logger.ts',
    'utils': 'src/utils.ts',
    'types': 'src/types.ts',
    'workers': 'src/workers/index.ts',
    'adapters/axiom': 'src/adapters/axiom.ts',
    'adapters/otlp': 'src/adapters/otlp.ts',
    'adapters/posthog': 'src/adapters/posthog.ts',
    'adapters/sentry': 'src/adapters/sentry.ts',
    'adapters/better-stack': 'src/adapters/better-stack.ts',
    'enrichers': 'src/enrichers/index.ts',
    'pipeline': 'src/pipeline.ts',
    'browser': 'src/browser.ts',
    'next/index': 'src/next/index.ts',
    'next/client': 'src/next/client.ts',
    'hono/index': 'src/hono/index.ts',
    'express/index': 'src/express/index.ts',
    'elysia/index': 'src/elysia/index.ts',
    'fastify/index': 'src/fastify/index.ts',
    'nestjs/index': 'src/nestjs/index.ts',
    'sveltekit/index': 'src/sveltekit/index.ts',
    'toolkit': 'src/shared/index.ts',
  },
  format: 'esm',
  dts: true,
  clean: true,
  fixedExtension: true,
  external: [
    '#app',
    '#imports',
    'vue',
    'nuxt',
    '@nuxt/kit',
    '@nuxt/schema',
    'nitropack',
    'nitropack/runtime',
    'nitropack/kit',
    'nitropack/types',
    'nitro',
    'nitro/h3',
    'nitro/runtime-config',
    'nitro/types',
    'ofetch',
    'h3',
    'next',
    'next/server',
    'react',
    'hono',
    'hono/factory',
    'express',
    'elysia',
    'fastify',
    '@nestjs/common',
    '@nestjs/core',
    '@sveltejs/kit',
  ],
  inlineOnly: ['ufo']
})
