import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, relative, resolve } from 'node:path'
import { addTemplate, defineNuxtModule } from '@nuxt/kit'

/**
 * Where the things being filmed come from.
 *
 * The lab used to reach into a sibling app by relative path, hard-coded in three
 * places. That made it evlog's lab rather than a lab: nobody else could point it
 * at their own components, and nothing could be built without that sibling on
 * disk. Here the sources are configuration, so filming evlog's documentation is
 * one entry in a list rather than an assumption baked into the source.
 *
 * A glob rather than a manifest, because a hand-written list of components is a
 * second thing to keep in step with the first — add an animation and it is
 * stageable, delete it and it stops being an option.
 */
export interface StageSource {
  /**
   * Glob of stageable components, absolute or relative to the project root.
   *
   * Resolved here and rewritten relative to the generated module, because
   * `import.meta.glob` is evaluated where it is written, not where it is
   * configured.
   */
  glob: string
  /** Shown in the picker to tell one body of work from another. */
  group?: string
  /**
   * Stylesheet the components need, if they do not carry their own.
   *
   * Filming a component out of its own app means leaving its design tokens
   * behind, and a plate rasterized without them is the right layout in the wrong
   * type and colours.
   */
  css?: string
  /**
   * Directory Tailwind should scan for class names.
   *
   * Utilities used only by a staged component live outside this project, so
   * nothing here would generate them and the plate would come out unstyled.
   */
  source?: string
}

export interface StagesOptions {
  sources?: StageSource[]
}

export default defineNuxtModule<StagesOptions>({
  meta: {
    name: 'render-labs-stages',
    configKey: 'stages',
  },

  defaults: {
    sources: [],
  },

  setup(options, nuxt) {
    const root = nuxt.options.rootDir
    const sources = (options.sources ?? []).filter((source) => {
      // A source whose files are absent is a stale entry or a sibling that was
      // never checked out. Skipping it with a word is friendlier than a build
      // that fails inside a glob nobody wrote by hand.
      const base = globBase(resolve(root, source.glob))
      if (existsSync(base)) return true
      console.warn(`[render-labs] stage source skipped, nothing at ${base}`)
      return false
    })

    /**
     * Written to disk inside the project rather than emitted as a template.
     *
     * Nuxt serves templates as virtual modules, and Vite requires every glob in
     * a virtual module to start at the Vite root — which the sources, being in
     * another project entirely, cannot. A real file has no such rule, and the
     * relative paths from it resolve the way any import would.
     */
    const generatedDir = resolve(root, '.stages')
    const generated = resolve(generatedDir, 'index.ts')

    const entries = sources.map((source, index) => {
      const absolute = resolve(root, source.glob)
      // Vite reads the literal, so it has to be a path relative to this file —
      // and one that starts with a dot, or it is taken for a package.
      const path = withLeadingDot(relative(generatedDir, absolute))
      return `  ...withGroup(import.meta.glob(${JSON.stringify(path)}), ${JSON.stringify(source.group ?? `group-${index}`)}),`
    })

    mkdirSync(generatedDir, { recursive: true })
    writeFileSync(generated, `// Generated by modules/stages.ts — edit \`stages\` in nuxt.config instead.
import type { Component } from 'vue'

type Loader = () => Promise<{ default: Component }>

function withGroup(modules: Record<string, unknown>, group: string): Record<string, { group: string, load: Loader }> {
  return Object.fromEntries(
    Object.entries(modules).map(([path, load]) => [path, { group, load: load as Loader }]),
  )
}

export const STAGE_MODULES: Record<string, { group: string, load: Loader }> = {
${entries.join('\n')}
}
`)

    nuxt.options.alias['#render-labs/stages'] = generated

    // Tailwind scans the importing project only, and every utility a staged
    // component uses lives outside it. Declared here so a source brings its own
    // styling with it rather than needing a second edit in the stylesheet.
    const scanned = sources.map(source => source.source).filter((path): path is string => Boolean(path))
    if (scanned.length) {
      const sheet = addTemplate({
        filename: 'render-labs-stage-sources.css',
        write: true,
        getContents: () => `${scanned.map(path => `@source ${JSON.stringify(resolve(root, path))};`).join('\n')}\n`,
      })
      nuxt.options.css.push(sheet.dst)
    }

    for (const source of sources) {
      if (source.css) nuxt.options.css.push(resolve(root, source.css))
    }

    // The sources sit outside the project root, which Vite refuses to serve from
    // in development unless it is told they are expected.
    nuxt.options.vite.server ??= {}
    nuxt.options.vite.server.fs ??= {}
    const allow = nuxt.options.vite.server.fs.allow ?? []
    nuxt.options.vite.server.fs.allow = [
      ...allow,
      ...sources.map(source => globBase(resolve(root, source.glob))),
    ]
  },
})

/** The fixed part of a glob, which is the part that either exists or does not. */
function globBase(pattern: string): string {
  const cut = pattern.search(/[*?[{]/)
  return cut === -1 ? pattern : dirname(pattern.slice(0, cut))
}

function withLeadingDot(path: string): string {
  return isAbsolute(path) || path.startsWith('.') ? path : `./${path}`
}
