import { existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { Plugin } from 'vite'
import MagicString from 'magic-string'
import type { AutoImportsOptions } from './types'
import { TRANSFORM_FILTER, shouldTransform, walk } from './utils'

const DEFAULT_IMPORTS = ['log', 'createEvlogError', 'parseError']
const LOG_METHODS = ['info', 'error', 'warn', 'debug']

const IMPORT_SOURCES: Record<string, string> = {
  log: 'evlog',
  createEvlogError: 'evlog',
  parseError: 'evlog',
  setIdentity: 'evlog/client',
  clearIdentity: 'evlog/client',
}

export function createAutoImportsPlugin(options: AutoImportsOptions = {}): Plugin {
  const symbols = options.imports ?? DEFAULT_IMPORTS

  return {
    name: 'evlog:auto-imports',

    configResolved(config) {
      if (options.dts === false) return
      if (typeof options.dts === 'string') {
        writeFileSync(resolve(config.root, options.dts), generateDts(symbols))
        return
      }
      const srcDir = resolve(config.root, 'src')
      const dir = existsSync(srcDir) ? srcDir : config.root
      writeFileSync(resolve(dir, 'auto-imports.d.ts'), generateDts(symbols))
    },

    transform: {
      filter: TRANSFORM_FILTER,
      handler(code, id) {
        if (!shouldTransform(id)) return
        if (!symbols.some(s => code.includes(s))) return

        let ast: any
        try {
          ast = (this as any).parse(code)
        } catch {
          return
        }

        const declared = collectTopLevelDeclarations(ast)
        const needed = detectUsedSymbols(ast, symbols, declared)

        if (needed.size === 0) return

        const grouped = groupBySource(needed)
        const s = new MagicString(code)

        for (const [source, names] of grouped) {
          s.prepend(`import { ${names.join(', ')} } from '${source}'\n`)
        }

        return { code: s.toString(), map: s.generateMap({ hires: true }) }
      },
    },
  }
}

function collectBindingNames(pattern: any, out: Set<string>): void {
  if (!pattern) return
  if (pattern.type === 'Identifier') {
    out.add(pattern.name)
  } else if (pattern.type === 'ObjectPattern') {
    for (const prop of pattern.properties) {
      collectBindingNames(prop.type === 'RestElement' ? prop.argument : prop.value, out)
    }
  } else if (pattern.type === 'ArrayPattern') {
    for (const el of pattern.elements) {
      if (el) collectBindingNames(el, out)
    }
  } else if (pattern.type === 'AssignmentPattern') {
    collectBindingNames(pattern.left, out)
  } else if (pattern.type === 'RestElement') {
    collectBindingNames(pattern.argument, out)
  }
}

function collectTopLevelDeclarations(ast: any): Set<string> {
  const declared = new Set<string>()
  for (const node of ast.body) {
    if (node.type === 'VariableDeclaration') {
      for (const decl of node.declarations) {
        collectBindingNames(decl.id, declared)
      }
    }
    if (node.type === 'FunctionDeclaration' && node.id?.name) {
      declared.add(node.id.name)
    }
    if (node.type === 'ImportDeclaration') {
      for (const spec of node.specifiers ?? []) {
        if (spec.local?.name) declared.add(spec.local.name)
      }
    }
  }
  return declared
}

function detectUsedSymbols(ast: any, symbols: string[], declared: Set<string>): Set<string> {
  const needed = new Set<string>()

  walk(ast, (node: any) => {
    if (
      symbols.includes('log')
      && !declared.has('log')
      && node.type === 'MemberExpression'
      && node.object?.type === 'Identifier'
      && node.object.name === 'log'
      && node.property?.type === 'Identifier'
      && LOG_METHODS.includes(node.property.name)
    ) {
      needed.add('log')
    }

    if (
      node.type === 'CallExpression'
      && node.callee?.type === 'Identifier'
      && symbols.includes(node.callee.name)
      && !declared.has(node.callee.name)
    ) {
      needed.add(node.callee.name)
    }
  })

  return needed
}

function groupBySource(symbols: Set<string>): Map<string, string[]> {
  const map = new Map<string, string[]>()
  for (const sym of symbols) {
    const source = IMPORT_SOURCES[sym] ?? 'evlog'
    const list = map.get(source) ?? []
    list.push(sym)
    map.set(source, list)
  }
  return map
}

function generateDts(symbols: string[]): string {
  const lines = [
    '/* eslint-disable */',
    '// Generated by evlog/vite — do not edit',
    'export {}',
    'declare global {',
  ]

  for (const sym of symbols) {
    switch (sym) {
      case 'log':
        lines.push('  const log: import(\'evlog\').Log')
        break
      case 'createEvlogError':
        lines.push('  const createEvlogError: typeof import(\'evlog\').createEvlogError')
        break
      case 'parseError':
        lines.push('  const parseError: typeof import(\'evlog\').parseError')
        break
      case 'setIdentity':
        lines.push('  const setIdentity: (identity: Record<string, unknown>) => void')
        break
      case 'clearIdentity':
        lines.push('  const clearIdentity: () => void')
        break
      default:
        lines.push(`  const ${sym}: typeof import('evlog').${sym}`)
        break
    }
  }

  lines.push('}', '')
  return lines.join('\n')
}
